on: [pull_request]

jobs:
  build-chain:
    runs-on: ubuntu-latest
    name: Build Pull Request
    steps:
    - uses: actions/checkout@v2
    - name: Build Chain
      id: build-chain
      uses: kiegroup/github-action-build-chain@master
      with:
        parent-dependencies: 'optaweb-vehicle-routing'
        build-command: 'mvn -e -nsu clean install -Dfull -Prun-code-coverage -Pwildfly -Dcontainer=wildfly -Dcontainer.profile=wildfly -Dintegration-tests=true -Dmaven.test.failure.ignore=true -Pbusiness-central -Dgwt.compiler.localWorkers=1 -Dwebdriver.firefox.bin=/opt/tools/firefox-60esr/firefox-bin -DjvmArgs="-Xms1g -Xmx4g"'
        build-command-upstream: "mvn -e -T1C clean install -DskipTests -Dgwt.compiler.skip=true -Dgwt.skipCompilation=true -Denforcer.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Drevapi.skip=true"
      env:
          GITHUB_TOKEN: "${{ secrets.KIE_TOKEN }}"
